### ISSUE TITLE
Maven package?

### ISSUE THREAD

**Issue by DarrienG** [hdevalke/result4j#1]
This looks super cool, is there a way to include this without manually pulling the code in?

**Comment by hdevalke** [comment]
I don't feel like maintaining this package. But nothing prevents you to fork it and do so.

**Comment by DarrienG** [comment]
🦀

**Comment by DarrienG** [comment]
Update - I found these guys which have a fully featured algebra package: https://github.com/HubSpot/algebra

Your repo pops up first if you Google `rust result java`. You may want to consider linking to them as an alternative.

**Comment by hdevalke** [comment]
Good point.

There is also https://www.functionaljava.org/ and https://www.vavr.io/ 
I'll reopen this ticket to add this to the readme.
